### ISSUE TITLE
Default settings dependent on stairsplus

### ISSUE THREAD

**Issue by ExcaliburZero** [VanessaE/moretrees#10]
Currently the moretrees mod by its default settings depend on the stairsplus mod, because it has a default setting of "moretrees.enable_stairsplus = true", which runs code that requires the use of stairsplus (and throws an error if the player does not have stairsplus). You may want to make the default setting for that false so that when people run the mod for the first time and don't have the stairsplus mod they won't get an error message about it.

**Comment by VanessaE** [comment]
Current moretrees code already checks for the presence of moreblocks (which supplies stairsplus) before evaluating that config option, so there shouldn't be any possibility of a crash there unless your copy of moreblocks does not supply stairsplus (in which case, it needs updated).
