### ISSUE TITLE
tree generation

### ISSUE THREAD

**Issue by Ardonel** [VanessaE/moretrees#12]
VanessaE,

I am trying to understand the tree generation in the moretrees mod so I can add support for them to the Treecapitator mod. Is the file Tree_models.lua the file where you define the tree models? I had some of the capitating partially working, but I don't really understand how the moretrees trees are generated, so I am not sure how much changing needs to be done to the treecapitator mod to successfully capitate moretrees trees cleanly.

Thank you for your time.

**Comment by VanessaE** [comment]
Some of the models are defined there, while some are built up in code with some simple decisions.  Because of the built-in engine randomness of the spawn_tree() call, it's impossible to predict the shape of a tree, so you'll have to walk the tree nodes manually.

**Comment by Ardonel** [comment]
Since the trunk size is defined, once a location for the trunk is established, all that needs is to walk up the trunk until leaves nodes are encountered, then start expanding the search radius to make sure all the leaves are found. I have noticed in my most recent world that the Giant Sequoia has a 4 block gap between the top and the rest near the top of the tree. I was thinking that maybe just check up for 8 more block to make sure the tree gets totally removed, after you run out of trunk nodes at the original trunk zone.

**Comment by VanessaE** [comment]
There's more discussion here:  https://github.com/HybridDog/treecapitator/issues/2

There's a plan for the engine to add an "ID" code to a tree to allow other mods to tell one from another.

**Comment by Ardonel** [comment]
Has there been any progress on merging "ID" code yet?
