### ISSUE TITLE
Stairs from Moretrees mod

### ISSUE THREAD

**Issue by Ardonel** [VanessaE/moretrees#13]
I must be missing something, but are stairs defined for the Moretrees mod? I thought the existed at one time, and I can can see the hook to Moreblocks\Stairsplus, but my game is not generating Moretrees stairs. I did enable the Stairsplus setting in default_settings.txt, but I still do not get moretrees stairs. Please, what am I missing?

PS - Minetest is compiled from Git about a week ago, Moretrees and Moreblocks are from 2 days ago.

**Comment by VanessaE** [comment]
Ah yep I forgot to add support for the default stairs mod.  Fixed, adecd4b1ea3e6e2ba481c8dabcfe038fa5ec50f8
