### ISSUE TITLE
Pine Trees are unknown Blocks after Update but Saplings grows into regular Pines fine

### ISSUE THREAD

**Issue by tchncs** [VanessaE/moretrees#17]
I updated all Servermods and Minetest this day.
Now the old Pines are unknown Blocks, the Leaves going away.
The Saplings growing up fine, but there are a lot of this trees in the Map :'(

![screenshot_20150821_141106](https://cloud.githubusercontent.com/assets/10698140/9408204/c1a539ac-4810-11e5-90c2-c1f57e190a6b.png)
![screenshot_20150821_141425](https://cloud.githubusercontent.com/assets/10698140/9408203/c1a49f88-4810-11e5-9cba-a54ace919603.png)

**Comment by VanessaE** [comment]
Update your minetest_game also.  Moretrees uses the default nodes for these.

**Comment by tchncs** [comment]
Of course i updated the minetest_game too.

**Comment by VanessaE** [comment]
Aw crap.  Looks like I forgot to fix an alias.  Sorry about that!  Fixed, fa3c3c60040b8ccdc5e0b5ab0f63d21a3b4422f9.

**Comment by tchncs** [comment]
Jey, thank you very much for fixing <3
![screenshot_20150821_150944](https://cloud.githubusercontent.com/assets/10698140/9408913/b86da800-4816-11e5-9f6b-9b37708f1d66.png)

**Comment by VanessaE** [comment]
No prob.  Time to re-plant a few trees.  Tip:  Admins can use moretrees:pine_sapling_ongen and other "_ongen" saplings to get results MUCH faster than with the normal ones.

**Comment by tchncs** [comment]
Oh, cool, thank you, thats explains something i asked me in the past :D

**Comment by Megaf** [comment]
Pine trees still using unknown blocks. And there is this crash, https://github.com/VanessaE/moretrees/issues/18 I don't know if it's related to this bug or not.

**Comment by VanessaE** [comment]
If you're seeing unknown nodes for the pine trees, your minetest_game is still too old, or you need to re-pull moretrees.
