### ISSUE TITLE
moretrees:stair_acacia_planks = unknown Blocks

### ISSUE THREAD

**Issue by tchncs** [VanessaE/moretrees#19]
moretrees:stair_acacia_planks are unknown Blocks now.

![bildschirmfoto vom 2015-08-31 13-36-10](https://cloud.githubusercontent.com/assets/10698140/9577976/76c85e4a-4fe6-11e5-9e30-43747b25aa16.png)

this problem happends with moreblocks_slap_pinewood_2 too... seems like i write two issues this day :-P

****

Of course, minetest and minetest_game are on the latest commit. :-)

**Comment by VanessaE** [comment]
Upgrade your Minetest engine and minetest_game to 0.4.13, and also update your More Blocks mod.

You'll have to replace the stairs with newly-made ones, as the node names have changed to use the default ones that come with minetest_game.  An ABM could have been added to Moretrees to handle this case, but I didn't figure it was worth the effort.
