### ISSUE TITLE
sapling still spawning even though disabled

### ISSUE THREAD

**Issue by sofar** [VanessaE/moretrees#20]
I have a moretrees.settings file named ```moretrees_settings.txt``` in my world folder, with this content:

```
moretrees.spawn_saplings = false
moretrees.enable_apple_tree = false
moretrees.enable_oak = false
moretrees.enable_sequoia = false
moretrees.enable_palm = false
moretrees.enable_pine = false
moretrees.enable_rubber_tree = false
moretrees.enable_willow = false
moretrees.enable_acacia = false
moretrees.enable_birch = false
moretrees.enable_spruce = false
moretrees.enable_jungle_tree = false
moretrees.enable_fir = false
moretrees.enable_beech = false
```

However, Saplings are still appearing on this map. Spruce is causing major annoyances :(

**Comment by sofar** [comment]
I think these appeared at mapgen time as well. The mapgen itself does not create spruce trees (it's valleys - the lua version), so I'm wondering if moretrees leaves the decorations for mapgen enabled.

**Comment by sofar** [comment]
PEBKAC. Ignore the noise.

**Comment by VanessaE** [comment]
Ok, I must know, what went wrong? :smile:

**Comment by sofar** [comment]
My initial converted map had spruce saplings still looming in a few corners (mcimport.py). Hence while I was thinking it was moretrees, it was the pristine converted result from MC.

**Comment by sofar** [comment]
Needless to say I'm no longer converting MC pine trees to moretrees:pine, since that doesn't make much sense (those are way, way larger).
