### ISSUE TITLE
Light/shadow issues

### ISSUE THREAD

**Issue by greencopper** [VanessaE/moretrees#22]
Hi Vanessa

The last couple of times I have tried to add the more trees mod I have lots of issues with light/shadows, see attached shots.

Also sometimes when a tree is cut down (no more tree) the shadow stays.

Kind regards
![shot1](https://cloud.githubusercontent.com/assets/1302896/13031377/d41f12b4-d2cc-11e5-923a-2562794a65fc.png)
![shot2](https://cloud.githubusercontent.com/assets/1302896/13031378/d4227b8e-d2cc-11e5-9a55-c8396598107b.png)

But I don't suspect it's the moretree mods in itself, because once removed and we get "unknown blocks" instead, the shadow problem persists.

![shot1](https://cloud.githubusercontent.com/assets/1302896/13031401/65521aa6-d2cd-11e5-846f-7cc4937b0fc2.png)
![shot2](https://cloud.githubusercontent.com/assets/1302896/13031402/6552b934-d2cd-11e5-94a1-1a188b9fc6c0.png)

**Comment by VanessaE** [comment]
@paramat here's another one :-/

greencopper, don't run Moretrees on a mapgen v7 world.  Or if you must, set it to generate only saplings at mapgen time.

**Comment by paramat** [comment]
It's an engine issue with l-system trees.causing shadows when spawned close to mapgen time, as far as i know it's when the mapchunk above has not yet been generated.

**Comment by 0-afflatus** [comment]
I find /mapfix to be an acceptable temporary workaround. It allows players to fix up small areas if they come across them. This way the bug is not a showstopper. I run moretrees with v7 mapgen and it's playable.
